import { User, Squad, Task, JiraTicket, TestpadRun } from '../types';

export const SQUAD_COLORS: Record<string, string> = {
  ESERV: '#4CBFB1',
  FINSERV: '#6B8EFF',
  INFRASTRUCTURE: '#F59E0B',
  OPS: '#EC4899',
  'STORE APP RELEASE': '#8B5CF6',
  'STORE FRONTS': '#10B981',
};

export const SQUADS_CONFIG: Record<string, string[]> = {
  ESERV: ['2026 Sprint 1', 'Sprint 4'],
  FINSERV: ['Sprint 1', 'Sprint 2', 'Sprint 3', 'Sprint 4'],
  INFRASTRUCTURE: ['Store Network', 'Common Service', 'GrowCube', 'Mobile Platform', '1WS'],
  OPS: ['LM & BH', 'PSP App', 'Supply Grow & MS'],
  'STORE APP RELEASE': ['Tech Debt', 'Sprint 1', 'Sprint 2'],
  'STORE FRONTS': ['Ecommerce', 'Web & Merchant Admin'],
};

export const DEMO_USERS: User[] = [
  {
    id: 'u1',
    username: 'admin',
    name: 'Maria Santos',
    role: 'manager',
    squad: 'OPS',
    status: 'active',
    projects: ['LM & BH', 'PSP App'],
    currentTask: 'Q1 QA Planning & Review',
    capacity: 85,
  },
  {
    id: 'u2',
    username: 'qa.you',
    name: 'You (QA Engineer)',
    role: 'qa',
    squad: 'OPS',
    status: 'active',
    projects: ['LM & BH', 'Supply Grow & MS'],
    currentTask: 'Regression Testing - LM Sprint 2',
    capacity: 70,
  },
  {
    id: 'u3',
    username: 'qa.reyes',
    name: 'Carlos Reyes',
    role: 'qa',
    squad: 'ESERV',
    status: 'busy',
    projects: ['2026 Sprint 1', 'Sprint 4'],
    currentTask: 'API Test Automation - ESERV Sprint 1',
    capacity: 90,
  },
  {
    id: 'u4',
    username: 'qa.dela',
    name: 'Ana Dela Cruz',
    role: 'qa',
    squad: 'FINSERV',
    status: 'active',
    projects: ['Sprint 1', 'Sprint 2'],
    currentTask: 'Smoke Testing - FINSERV Sprint 2',
    capacity: 60,
  },
  {
    id: 'u5',
    username: 'qa.tan',
    name: 'Kevin Tan',
    role: 'qa',
    squad: 'FINSERV',
    status: 'available',
    projects: ['Sprint 3', 'Sprint 4'],
    currentTask: undefined,
    capacity: 20,
  },
  {
    id: 'u6',
    username: 'qa.garcia',
    name: 'Lisa Garcia',
    role: 'qa',
    squad: 'INFRASTRUCTURE',
    status: 'active',
    projects: ['Store Network', 'Common Service'],
    currentTask: 'E2E Suite for Store Network',
    capacity: 75,
  },
  {
    id: 'u7',
    username: 'qa.lim',
    name: 'James Lim',
    role: 'qa',
    squad: 'INFRASTRUCTURE',
    status: 'busy',
    projects: ['GrowCube', 'Mobile Platform', '1WS'],
    currentTask: 'Mobile Platform Performance Testing',
    capacity: 95,
  },
  {
    id: 'u8',
    username: 'qa.bautista',
    name: 'Rose Bautista',
    role: 'qa',
    squad: 'OPS',
    status: 'active',
    projects: ['PSP App'],
    currentTask: 'PSP Payment Flow Testing',
    capacity: 65,
  },
  {
    id: 'u9',
    username: 'qa.mendoza',
    name: 'Rico Mendoza',
    role: 'qa',
    squad: 'STORE APP RELEASE',
    status: 'on_leave',
    projects: ['Tech Debt', 'Sprint 1'],
    currentTask: undefined,
    capacity: 0,
  },
  {
    id: 'u10',
    username: 'qa.cruz',
    name: 'Pia Cruz',
    role: 'qa',
    squad: 'STORE APP RELEASE',
    status: 'active',
    projects: ['Sprint 2'],
    currentTask: 'Release Candidate Validation',
    capacity: 80,
  },
  {
    id: 'u11',
    username: 'qa.villanueva',
    name: 'Mark Villanueva',
    role: 'qa',
    squad: 'STORE FRONTS',
    status: 'active',
    projects: ['Ecommerce'],
    currentTask: 'Checkout Flow Regression',
    capacity: 70,
  },
  {
    id: 'u12',
    username: 'qa.torres',
    name: 'Jenna Torres',
    role: 'qa',
    squad: 'STORE FRONTS',
    status: 'available',
    projects: ['Web & Merchant Admin'],
    currentTask: undefined,
    capacity: 30,
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Regression Testing - LM Sprint 2',
    assigneeId: 'u2',
    squad: 'OPS',
    project: 'LM & BH',
    status: 'in_progress',
    priority: 'high',
    jiraKey: 'OPS-1042',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-10',
    dueDate: '2026-03-15',
    description: 'Full regression suite for LM Sprint 2 release candidate.',
  },
  {
    id: 't2',
    title: 'API Test Automation - ESERV Sprint 1',
    assigneeId: 'u3',
    squad: 'ESERV',
    project: '2026 Sprint 1',
    status: 'in_progress',
    priority: 'critical',
    jiraKey: 'ESERV-334',
    createdAt: '2026-02-28',
    updatedAt: '2026-03-11',
    dueDate: '2026-03-14',
  },
  {
    id: 't3',
    title: 'Smoke Testing - FINSERV Sprint 2',
    assigneeId: 'u4',
    squad: 'FINSERV',
    project: 'Sprint 2',
    status: 'in_progress',
    priority: 'medium',
    jiraKey: 'FIN-788',
    createdAt: '2026-03-05',
    updatedAt: '2026-03-12',
    dueDate: '2026-03-16',
  },
  {
    id: 't4',
    title: 'E2E Suite for Store Network',
    assigneeId: 'u6',
    squad: 'INFRASTRUCTURE',
    project: 'Store Network',
    status: 'in_progress',
    priority: 'high',
    jiraKey: 'INFRA-201',
    createdAt: '2026-03-03',
    updatedAt: '2026-03-10',
    dueDate: '2026-03-18',
  },
  {
    id: 't5',
    title: 'Mobile Platform Performance Testing',
    assigneeId: 'u7',
    squad: 'INFRASTRUCTURE',
    project: 'Mobile Platform',
    status: 'blocked',
    priority: 'critical',
    jiraKey: 'INFRA-215',
    createdAt: '2026-03-04',
    updatedAt: '2026-03-13',
    dueDate: '2026-03-15',
    description: 'Blocked on environment setup. Waiting for DevOps.',
  },
  {
    id: 't6',
    title: 'PSP Payment Flow Testing',
    assigneeId: 'u8',
    squad: 'OPS',
    project: 'PSP App',
    status: 'in_progress',
    priority: 'high',
    jiraKey: 'OPS-1055',
    createdAt: '2026-03-06',
    updatedAt: '2026-03-12',
    dueDate: '2026-03-17',
  },
  {
    id: 't7',
    title: 'Release Candidate Validation',
    assigneeId: 'u10',
    squad: 'STORE APP RELEASE',
    project: 'Sprint 2',
    status: 'in_progress',
    priority: 'critical',
    jiraKey: 'SAR-145',
    createdAt: '2026-03-07',
    updatedAt: '2026-03-13',
    dueDate: '2026-03-14',
  },
  {
    id: 't8',
    title: 'Checkout Flow Regression',
    assigneeId: 'u11',
    squad: 'STORE FRONTS',
    project: 'Ecommerce',
    status: 'in_progress',
    priority: 'high',
    jiraKey: 'SF-390',
    createdAt: '2026-03-08',
    updatedAt: '2026-03-12',
    dueDate: '2026-03-16',
  },
  {
    id: 't9',
    title: 'Supply Grow Integration Tests',
    assigneeId: 'u2',
    squad: 'OPS',
    project: 'Supply Grow & MS',
    status: 'not_started',
    priority: 'medium',
    jiraKey: 'OPS-1060',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-10',
    dueDate: '2026-03-20',
  },
  {
    id: 't10',
    title: 'FINSERV Sprint 4 Test Planning',
    assigneeId: 'u5',
    squad: 'FINSERV',
    project: 'Sprint 4',
    status: 'not_started',
    priority: 'low',
    jiraKey: 'FIN-800',
    createdAt: '2026-03-11',
    updatedAt: '2026-03-11',
    dueDate: '2026-03-25',
  },
];

export const MOCK_JIRA_TICKETS: JiraTicket[] = [
  { key: 'OPS-1042', summary: 'LM Sprint 2 Regression', status: 'In Progress', assignee: 'qa.you', priority: 'High', updated: '2026-03-10', project: 'LM & BH' },
  { key: 'OPS-1055', summary: 'PSP Payment Flow QA', status: 'In Progress', assignee: 'qa.bautista', priority: 'High', updated: '2026-03-12', project: 'PSP App' },
  { key: 'OPS-1060', summary: 'Supply Grow Integration Tests', status: 'To Do', assignee: 'qa.you', priority: 'Medium', updated: '2026-03-10', project: 'Supply Grow & MS' },
  { key: 'ESERV-334', summary: 'API Automation Sprint 1', status: 'In Progress', assignee: 'qa.reyes', priority: 'Critical', updated: '2026-03-11', project: '2026 Sprint 1' },
  { key: 'FIN-788', summary: 'Smoke Test Sprint 2', status: 'In Progress', assignee: 'qa.dela', priority: 'Medium', updated: '2026-03-12', project: 'Sprint 2' },
  { key: 'FIN-800', summary: 'Sprint 4 Test Plan', status: 'To Do', assignee: 'qa.tan', priority: 'Low', updated: '2026-03-11', project: 'Sprint 4' },
  { key: 'INFRA-201', summary: 'Store Network E2E Suite', status: 'In Progress', assignee: 'qa.garcia', priority: 'High', updated: '2026-03-10', project: 'Store Network' },
  { key: 'INFRA-215', summary: 'Mobile Platform Perf Test', status: 'Blocked', assignee: 'qa.lim', priority: 'Critical', updated: '2026-03-13', project: 'Mobile Platform' },
  { key: 'SAR-145', summary: 'RC Validation Sprint 2', status: 'In Progress', assignee: 'qa.cruz', priority: 'Critical', updated: '2026-03-13', project: 'Sprint 2' },
  { key: 'SF-390', summary: 'Checkout Regression Suite', status: 'In Progress', assignee: 'qa.villanueva', priority: 'High', updated: '2026-03-12', project: 'Ecommerce' },
];

export const MOCK_TESTPAD_RUNS: TestpadRun[] = [
  { id: 'tp1', name: 'LM Sprint 2 Regression', status: 'running', progress: 68, total: 120, passed: 74, failed: 5, blocked: 3, assignee: 'qa.you', project: 'LM & BH' },
  { id: 'tp2', name: 'PSP Payment Flow', status: 'running', progress: 45, total: 80, passed: 32, failed: 2, blocked: 2, assignee: 'qa.bautista', project: 'PSP App' },
  { id: 'tp3', name: 'ESERV API Suite', status: 'running', progress: 82, total: 200, passed: 155, failed: 8, blocked: 1, assignee: 'qa.reyes', project: '2026 Sprint 1' },
  { id: 'tp4', name: 'FINSERV Smoke Sprint 2', status: 'running', progress: 55, total: 60, passed: 30, failed: 1, blocked: 2, assignee: 'qa.dela', project: 'Sprint 2' },
  { id: 'tp5', name: 'Store Network E2E', status: 'running', progress: 40, total: 150, passed: 56, failed: 4, blocked: 0, assignee: 'qa.garcia', project: 'Store Network' },
  { id: 'tp6', name: 'Mobile Platform Perf', status: 'blocked', progress: 20, total: 90, passed: 16, failed: 0, blocked: 2, assignee: 'qa.lim', project: 'Mobile Platform' },
  { id: 'tp7', name: 'RC Validation Sprint 2', status: 'running', progress: 75, total: 100, passed: 70, failed: 3, blocked: 2, assignee: 'qa.cruz', project: 'Sprint 2' },
  { id: 'tp8', name: 'Checkout Regression', status: 'running', progress: 60, total: 110, passed: 62, failed: 2, blocked: 4, assignee: 'qa.villanueva', project: 'Ecommerce' },
];

export const CREDENTIALS: Record<string, { password: string; userId: string }> = {
  'admin': { password: 'test123', userId: 'u1' },
  'qa.you': { password: 'test123', userId: 'u2' },
  'qa.reyes': { password: 'test123', userId: 'u3' },
  'qa.dela': { password: 'test123', userId: 'u4' },
  'qa.tan': { password: 'test123', userId: 'u5' },
  'qa.garcia': { password: 'test123', userId: 'u6' },
  'qa.lim': { password: 'test123', userId: 'u7' },
  'qa.bautista': { password: 'test123', userId: 'u8' },
  'qa.mendoza': { password: 'test123', userId: 'u9' },
  'qa.cruz': { password: 'test123', userId: 'u10' },
  'qa.villanueva': { password: 'test123', userId: 'u11' },
  'qa.torres': { password: 'test123', userId: 'u12' },
};
